# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GordonBeeming.CopilotHere
PackageVersion: 2026.10.08.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: copilot_here.exe
  PortableCommandAlias: copilot_here
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/GordonBeeming/copilot_here/releases/download/cli-v2026.10.08.1-428859a/copilot_here-win-x64.zip
  InstallerSha256: 115A28EB6A8DB749AEFBDEFAFCA8F6D7CA7F2CC06D04FA509A64AD1BAE7E1B7B
- Architecture: arm64
  InstallerUrl: https://github.com/GordonBeeming/copilot_here/releases/download/cli-v2026.10.08.1-428859a/copilot_here-win-arm64.zip
  InstallerSha256: 6337C53790701710488C6613208CD1898993170884396182195389268F5B5BEA
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-08
