# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GordonBeeming.CopilotHere
PackageVersion: 2026.10.07.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: copilot_here.exe
  PortableCommandAlias: copilot_here
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/GordonBeeming/copilot_here/releases/download/cli-v2026.10.07.1-aa3b159/copilot_here-win-x64.zip
  InstallerSha256: 68533DC7CCBD15779EF9789BD44666232096F3CD036817735729678E4ED2E0E0
- Architecture: arm64
  InstallerUrl: https://github.com/GordonBeeming/copilot_here/releases/download/cli-v2026.10.07.1-aa3b159/copilot_here-win-arm64.zip
  InstallerSha256: B948D74AB091BF5937D099F3FE3EAA6D132573C6649252955614284ECB1AB8A0
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-07
